#############################################################################
##
#A  simsgroup.jl                                                      OrbitAl
#B    by Götz Pfeiffer <goetz.pfeiffer@universityofgalway.ie>
##
#C  The Schreier-Sims algorithm, and backtrack search
##
##  A stabilizer chain is a list of links, each with a base point, the
##  strong generators that fix the earlier base points, the orbit of
##  the base point and a transversal.
##
module simsgroup

import Base: intersect

using ..orbits: orbit, onPoints
import ..permutation: Perm, isidentity, last_moved
import ..permgroup: APermGp, sizeOfGroup, memberOfGroup, randomGroupElement

export ASimsGp, SimsGp, stabChain, cube
export Link, sift, schreier_sims, base, strong_gens
export backtrack, subgp_gens

"""
    Link(point, gens, id)

A link of a stabilizer chain: the base `point`, the generators `gens` of the
stabilizer of the earlier base points, the `orbit` of `point` under them, and
a transversal `reps`, which maps each point `y` of the orbit to an element
taking `point` to `y`.
"""
mutable struct Link
    point::Int
    gens::Vector{Perm}
    orbit::Vector{Int}
    reps::Dict{Int, Perm}
end

# recompute the orbit and the transversal, after a change of `link.gens`
function extend!(link::Link)
    id = link.reps[link.point]
    link.orbit = [link.point]
    link.reps = Dict(link.point => id)
    for y in link.orbit, a in link.gens
        z = y^a
        haskey(link.reps, z) || begin
            push!(link.orbit, z)
            link.reps[z] = link.reps[y] * a
        end
    end
    return link
end

Link(point, gens, id) = extend!(Link(point, gens, [point], Dict(point => id)))

"""
    sift(chain, g, i = 1)

Sift the permutation `g` through the links `i, i+1, ...` of `chain`.  Return
the residue and the first link where the image of the base point is not in
the orbit (or `length(chain) + 1`).  `g` lies in the group if and only if it
sifts through with residue the identity.
"""
function sift(chain, g, i = 1)
    while i <= length(chain)
        link = chain[i]
        y = link.point^g
        haskey(link.reps, y) || return g, i
        g = g / link.reps[y]
        i += 1
    end
    return g, i
end

# the first Schreier generator of link i that does not sift through
function schreier_test(chain, i)
    link = chain[i]
    for y in link.orbit, a in link.gens
        s = link.reps[y] * a / link.reps[y^a]
        h, j = sift(chain, s, i + 1)
        isidentity(h) || return h, j
    end
    return nothing, 0
end

"""
    schreier_sims(gens, id; base = Int[])

A stabilizer chain, as a list of `Link`s, of the group generated by `gens`,
by the Schreier-Sims algorithm.  The base starts with the points in `base`.
"""
function schreier_sims(gens, id; base = Int[])
    gens = filter(!isidentity, gens)
    isempty(base) && !isempty(gens) && (base = [last_moved(gens[1])])
    chain = [Link(b, l == 1 ? copy(gens) : Perm[], id) for (l, b) in enumerate(base)]
    i = 1
    while 1 <= i <= length(chain)
        h, j = schreier_test(chain, i)
        if isnothing(h)
            i -= 1
        else
            j > length(chain) && push!(chain, Link(last_moved(h), Perm[], id))
            for l in i+1:j
                push!(chain[l].gens, h)
                extend!(chain[l])
            end
            i = j
        end
    end
    return chain
end

"""
    sizeOfGroup(chain::Vector{Link})

The order of the group with stabilizer chain `chain`, as a `BigInt`: the
product of the orbit lengths along the chain.
"""
sizeOfGroup(chain::Vector{Link}) = prod(big(length(link.orbit)) for link in chain; init = big(1))

"""
    memberOfGroup(chain::Vector{Link}, g)

Whether the permutation `g` lies in the group with stabilizer chain `chain`:
whether it sifts through the chain.
"""
memberOfGroup(chain::Vector{Link}, g) = isidentity(first(sift(chain, g)))

"""
    randomGroupElement(chain::Vector{Link}, id)

A uniformly distributed random element of the group with stabilizer chain
`chain` and identity `id`: a product of random elements of the transversals
of the chain.
"""
randomGroupElement(chain::Vector{Link}, id) = prod(rand(collect(values(link.reps))) for link in reverse(chain); init = id)

"""
    base(chain)

The base points of the stabilizer chain `chain`.
"""
base(chain) = [link.point for link in chain]

"""
    strong_gens(chain)

The strong generating set of the stabilizer chain `chain`.
"""
strong_gens(chain) = unique(vcat([link.gens for link in chain]...))

"""
    ASimsGp

Abstract supertype for permutation groups with a stabilizer chain.  A subtype
has a method for `stabChain(G)`; then `sizeOfGroup`, `memberOfGroup`,
`randomGroupElement` and `∩` use the chain.
"""
abstract type ASimsGp <: APermGp end

sizeOfGroup(G::ASimsGp) = sizeOfGroup(stabChain(G))
memberOfGroup(G::ASimsGp, g::Perm) = memberOfGroup(stabChain(G), g)
randomGroupElement(G::ASimsGp) = randomGroupElement(stabChain(G), G.one)

"""
    SimsGp(gens, one)

A permutation group, given by generators `gens` and the identity `one`,
together with a stabilizer chain, which is computed when first needed.
"""
mutable struct SimsGp <: ASimsGp
    gens::Vector{Perm}
    one::Perm
    chain::Union{Nothing, Vector{Link}}
    SimsGp(gens, one) = new(gens, one, nothing)
end

"""
    stabChain(G::SimsGp)

The stabilizer chain of `G`, computed by `schreier_sims` on first use.
"""
function stabChain(G::SimsGp)
    isnothing(G.chain) && (G.chain = schreier_sims(G.gens, G.one))
    return G.chain
end

"""
    backtrack(chain, id, accept, prune = (g, i) -> true)

Search the elements of the group ``G`` with stabilizer chain `chain` depth
first, for those with `accept(g)`.  The elements form a tree, whose nodes at
depth ``i`` are the cosets ``G^{(i+1)} h`` of the stabilizers in the chain,
each represented by a partial product `h`.  A node at depth `i` is skipped,
together with the subtree below it, unless `prune(h, i)`.  Returns the
elements found, and the number of nodes visited.
"""
function backtrack(chain, id, accept, prune = (g, i) -> true)
    found = Perm[]
    nodes = 0
    function search(g, i)       # g fixes the images of b_1, ..., b_{i-1}
        nodes += 1
        if i > length(chain)
            accept(g) && push!(found, g)
            return
        end
        link = chain[i]
        for y in link.orbit
            h = link.reps[y] * g
            prune(h, i) && search(h, i + 1)
        end
    end
    search(id, 1)
    return (found = found, nodes = nodes)
end

# the first leaf with `accept` below the node g at depth i - 1, or nothing
function first_leaf(chain, g, i, accept, prune)    # g fixes the images of b_1, ..., b_{i-1}
    i > length(chain) && return accept(g) ? g : nothing
    link = chain[i]
    for y in link.orbit
        h = link.reps[y] * g
        prune(h, i) || continue
        f = first_leaf(chain, h, i + 1, accept, prune)
        isnothing(f) || return f
    end
    return nothing
end

"""
    subgp_gens(chain, accept, prune = (g, i) -> true)

Generators of the subgroup ``K = \\{g ∈ G : accept(g)\\}`` of the group ``G``
with stabilizer chain `chain`, by backtrack search, from the end of the
chain back to its start.  At link ``i``, a point already in the orbit of the
base point under the generators found so far needs no search.  `accept` must
define a subgroup, and `prune` must not skip a node with an element of ``K``
below it.
"""
function subgp_gens(chain, accept, prune = (g, i) -> true)
    gens = Perm[]
    for i in length(chain):-1:1
        link = chain[i]
        for y in link.orbit
            y in orbit(gens, link.point, onPoints) && continue
            t = link.reps[y]
            prune(t, i) || continue
            g = first_leaf(chain, t, i + 1, accept, prune)
            isnothing(g) || push!(gens, g)
        end
    end
    return gens
end

"""
    intersect(G::ASimsGp, H::ASimsGp)
    G ∩ H

The intersection of `G` and `H`, as a `SimsGp` with generators found by
`subgp_gens`: a node at depth ``i`` in the tree of ``G`` is pruned
unless it sifts through the first ``i`` links of a stabilizer chain of ``H``
with the same base.

# Examples
```jldoctest
julia> using OrbitAl, OrbitAl.simsgroup

julia> s = Perm([2,1,3,4]); t = Perm([1,3,2,4]); u = Perm([1,2,4,3]);

julia> G = SimsGp([s, t], one(s));  # S3 on {1,2,3}, order 6

julia> H = SimsGp([t, u], one(s));  # S3 on {2,3,4}, order 6

julia> K = G ∩ H;

julia> size(K)
2
```
"""
function intersect(G::ASimsGp, H::ASimsGp)
    chG = stabChain(G)
    chH = schreier_sims(H.gens, H.one; base = base(chG))
    prune(h, i) = sift(chH[1:i], h)[2] > i
    return SimsGp(subgp_gens(chG, g -> memberOfGroup(chH, g), prune), G.one)
end

## test data: Rubik's cube group
##
##                 +--------------+
##                 |              |
##                 |  1    2    3 |
##                 |              |
##                 |  4  top    5 |
##                 |              |
##                 |  6    7    8 |
##                 |              |
##  +--------------+--------------+--------------+--------------+
##  |              |              |              |              |
##  |  9   10   11 | 17   18   19 | 25   26   27 | 33   34   35 |
##  |              |              |              |              |
##  | 12  left  13 | 20 front  21 | 28 right  29 | 36  rear  37 |
##  |              |              |              |              |
##  | 14   15   16 | 22   23   24 | 30   31   32 | 38   39   40 |
##  |              |              |              |              |
##  +--------------+--------------+--------------+--------------+
##                 |              |
##                 | 41   42   43 |
##                 |              |
##                 | 44 bottom 45 |
##                 |              |
##                 | 46   47   48 |
##                 |              |
##                 +--------------+
##
cube = SimsGp([Perm(48, cycles) for cycles in [
  [[ 1, 3, 8, 6],[ 2, 5, 7, 4],[ 9,33,25,17],[10,34,26,18],[11,35,27,19]],
  [[ 9,11,16,14],[10,13,15,12],[ 1,17,41,40],[ 4,20,44,37],[ 6,22,46,35]],
  [[17,19,24,22],[18,21,23,20],[ 6,25,43,16],[ 7,28,42,13],[ 8,30,41,11]],
  [[25,27,32,30],[26,29,31,28],[ 3,38,43,19],[ 5,36,45,21],[ 8,33,48,24]],
  [[33,35,40,38],[34,37,39,36],[ 3, 9,46,32],[ 2,12,47,29],[ 1,14,48,27]],
  [[41,43,48,46],[42,45,47,44],[14,22,30,38],[15,23,31,39],[16,24,32,40]],
]], Perm(48))

end # module
