#############################################################################
##
#A  simsgroup.jl                                                      OrbitAl
#B    by Götz Pfeiffer <goetz.pfeiffer@universityofgalway.ie>
##
#C  The Schreier-Sims algorithm, and backtrack search
##
##  A stabilizer chain is a chain of links, each with a base point, the
##  strong generators that fix the earlier base points, the orbit of the
##  base point, a transversal, and the next link, for the stabilizer of the
##  base point.  The chain of the trivial group is `nothing`.
##
module simsgroup

import Base: intersect

using ..orbits: orbit, onPoints
import ..permutation: Perm, isidentity, last_moved
import ..permgroup: APermGp, sizeOfGroup, memberOfGroup, randomGroupElement

export ASimsGp, SimsGp, stabChain
export Link, sift, add!, schreier_sims, base, strong_gens
export backtrack, subgp_gens

"""
    Link(point, id, next = nothing)

A link of a stabilizer chain: the base `point`, the generators `gens` of the
stabilizer of the earlier base points, the `orbit` of `point` under them, a
transversal `reps`, which maps each point `y` of the orbit to an element
taking `point` to `y`, and the `next` link, for the stabilizer of `point`, or
`nothing` at the end of the chain.  A new link has no generators yet.
"""
mutable struct Link
    point::Int
    gens::Vector{Perm}
    orbit::Vector{Int}
    reps::Dict{Int, Perm}
    next::Union{Nothing, Link}
end

# recompute the orbit and the transversal, after a change of `link.gens`
function extend!(link::Link)
    id = link.reps[link.point]
    link.orbit = [link.point]
    link.reps = Dict(link.point => id)
    for y in link.orbit, a in link.gens
        z = y^a
        haskey(link.reps, z) || begin
            push!(link.orbit, z)
            link.reps[z] = link.reps[y] * a
        end
    end
    return link
end

Link(point, id, next = nothing) = Link(point, Perm[], [point], Dict(point => id), next)

"""
    sift(chain, g)

Sift the permutation `g` through the stabilizer chain `chain`, and return the
residue: `g` divided by transversal elements, link by link, up to the first
link where the image of the base point is not in the orbit.  `g` lies in the
group if and only if the residue is the identity.
"""
sift(::Nothing, g) = g

function sift(link::Link, g)
    y = link.point^g
    haskey(link.reps, y) || return g
    return sift(link.next, g / link.reps[y])
end

"""
    add!(link, h)

Add the permutation `h`, which fixes the earlier base points, to the
generators of `link`, and extend the rest of the chain by the Schreier
generators of `link` that do not sift through it.
"""
function add!(link::Link, h)                # h fixes the earlier base points
    push!(link.gens, h)
    extend!(link)
    for y in link.orbit, a in link.gens
        r = sift(link.next, link.reps[y] * a / link.reps[y^a])
        isidentity(r) && continue
        if isnothing(link.next)
            link.next = Link(last_moved(r), one(r))
        end
        add!(link.next, r)
    end
    return link
end

"""
    schreier_sims(gens, id; base = Int[])

A stabilizer chain of the group generated by `gens`, by the Schreier-Sims
algorithm: its first `Link`, or `nothing` for the trivial group.  The base
starts with the points in `base`.
"""
function schreier_sims(gens, id; base = Int[])
    gens = filter(!isidentity, gens)
    isempty(base) && !isempty(gens) && (base = [last_moved(gens[1])])
    chain = nothing
    for b in reverse(base)
        chain = Link(b, id, chain)
    end
    for a in gens
        isidentity(sift(chain, a)) || add!(chain, a)
    end
    return chain
end

"""
    sizeOfGroup(chain::Union{Nothing, Link})

The order of the group with stabilizer chain `chain`, as a `BigInt`: the
product of the orbit lengths along the chain.
"""
sizeOfGroup(::Nothing) = big(1)
sizeOfGroup(link::Link) = sizeOfGroup(link.next) * length(link.orbit)

"""
    memberOfGroup(chain::Union{Nothing, Link}, g)

Whether the permutation `g` lies in the group with stabilizer chain `chain`:
whether it sifts through the chain.
"""
memberOfGroup(chain::Union{Nothing, Link}, g) = isidentity(sift(chain, g))

"""
    randomGroupElement(chain::Union{Nothing, Link}, id)

A uniformly distributed random element of the group with stabilizer chain
`chain` and identity `id`: a product of random elements of the transversals
of the chain.
"""
randomGroupElement(::Nothing, id) = id
randomGroupElement(link::Link, id) = randomGroupElement(link.next, id) * rand(collect(values(link.reps)))

"""
    base(chain)

The base points of the stabilizer chain `chain`.
"""
base(::Nothing) = Int[]
base(link::Link) = [link.point; base(link.next)]

"""
    strong_gens(chain)

The strong generating set of the stabilizer chain `chain`.
"""
strong_gens(::Nothing) = Perm[]
strong_gens(link::Link) = union(link.gens, strong_gens(link.next))

"""
    ASimsGp

Abstract supertype for permutation groups with a stabilizer chain.  A subtype
has a method for `stabChain(G)`; then `sizeOfGroup`, `memberOfGroup`,
`randomGroupElement` and `∩` use the chain.
"""
abstract type ASimsGp <: APermGp end

sizeOfGroup(G::ASimsGp) = sizeOfGroup(stabChain(G))
memberOfGroup(G::ASimsGp, g::Perm) = memberOfGroup(stabChain(G), g)
randomGroupElement(G::ASimsGp) = randomGroupElement(stabChain(G), G.one)

"""
    SimsGp(gens, one)

A permutation group, given by generators `gens` and the identity `one`,
together with its stabilizer chain, computed by `schreier_sims`.
"""
struct SimsGp <: ASimsGp
    gens::Vector{Perm}
    one::Perm
    chain::Union{Nothing, Link}
    SimsGp(gens, one) = new(gens, one, schreier_sims(gens, one))
end

"""
    stabChain(G::SimsGp)

The stabilizer chain of `G`.
"""
stabChain(G::SimsGp) = G.chain

"""
    backtrack(chain, id, accept, prune = (g, i) -> true)

Search the elements of the group ``G`` with stabilizer chain `chain` depth
first, for those with `accept(g)`.  The elements form a tree, whose nodes at
depth ``i`` are the cosets ``G^{(i+1)} h`` of the stabilizers in the chain,
each represented by a partial product `h`.  A node at depth `i` is skipped,
together with the subtree below it, unless `prune(h, i)`.  Returns the
elements found, and the number of nodes visited.
"""
function backtrack(chain, id, accept, prune = (g, i) -> true)
    found = Perm[]
    nodes = 0
    function search(link, g, i)     # g fixes the images of b_1, ..., b_{i-1}
        nodes += 1
        if isnothing(link)
            accept(g) && push!(found, g)
            return
        end
        for y in link.orbit
            h = link.reps[y] * g
            prune(h, i) && search(link.next, h, i + 1)
        end
    end
    search(chain, id, 1)
    return (found = found, nodes = nodes)
end

# the first leaf with `accept` below the node g at depth i - 1, or nothing
function first_leaf(link, g, i, accept, prune)    # g fixes the images of b_1, ..., b_{i-1}
    isnothing(link) && return accept(g) ? g : nothing
    for y in link.orbit
        h = link.reps[y] * g
        prune(h, i) || continue
        f = first_leaf(link.next, h, i + 1, accept, prune)
        isnothing(f) || return f
    end
    return nothing
end

"""
    subgp_gens(chain, accept, prune = (g, i) -> true)

Generators of the subgroup ``K = \\{g ∈ G : accept(g)\\}`` of the group ``G``
with stabilizer chain `chain`, by backtrack search.  The generators of the
stabilizer ``K^{(i+1)}`` are found first, at the next link, recursively; then
a point already in the orbit of the base point under the generators found so
far needs no search.  `accept` must define a subgroup, and `prune` must not
skip a node with an element of ``K`` below it.
"""
function subgp_gens(link, accept, prune = (g, i) -> true, i = 1)
    isnothing(link) && return Perm[]
    gens = subgp_gens(link.next, accept, prune, i + 1)     # generators of K^(i+1)
    for y in link.orbit
        y in orbit(gens, link.point, onPoints) && continue
        t = link.reps[y]
        prune(t, i) || continue
        g = first_leaf(link.next, t, i + 1, accept, prune)
        isnothing(g) || push!(gens, g)
    end
    return gens
end

# does g sift through the first i links of the chain?
function sifts(link, g, i)
    i == 0 && return true
    y = link.point^g
    haskey(link.reps, y) || return false
    return sifts(link.next, g / link.reps[y], i - 1)
end

"""
    intersect(G::ASimsGp, H::ASimsGp)
    G ∩ H

The intersection of `G` and `H`, as a `SimsGp` with generators found by
`subgp_gens`: a node at depth ``i`` in the tree of ``G`` is pruned
unless it sifts through the first ``i`` links of a stabilizer chain of ``H``
with the same base.

# Examples
```jldoctest
julia> using OrbitAl, OrbitAl.simsgroup

julia> s = Perm([2,1,3,4]); t = Perm([1,3,2,4]); u = Perm([1,2,4,3]);

julia> G = SimsGp([s, t], one(s));  # S3 on {1,2,3}, order 6

julia> H = SimsGp([t, u], one(s));  # S3 on {2,3,4}, order 6

julia> K = G ∩ H;

julia> size(K)
2
```
"""
function intersect(G::ASimsGp, H::ASimsGp)
    chG = stabChain(G)
    chH = schreier_sims(H.gens, H.one; base = base(chG))
    gens = subgp_gens(chG, g -> memberOfGroup(chH, g), (h, i) -> sifts(chH, h, i))
    return SimsGp(gens, G.one)
end

end # module
