#############################################################################
##
#A  unionfind.jl                                                      OrbitAl
#B    by Götz Pfeiffer <goetz.pfeiffer@universityofgalway.ie>
##
#C  Union-Find, for equivalence relations and for linear relations
##
module unionfind

using ..sparsevec

export find, unite!

#############################################################################
##
##  Union-Find: an equivalence relation on 1:n, generated by pairs.
##
##  A forest is a list `parent` with `parent[i] == i` if `i` is a root.
##
"""
    find(parent::Vector{Int}, i)

The root of `i` in the forest `parent` is the smallest element of its class.
"""
function find(parent::Vector{Int}, i::Int)
    while parent[i] != i
        i = parent[i]
    end
    return i
end

"""
    unite!(parent::Vector{Int}, i, j)

Add the relation `i ~ j` to the forest `parent`: the larger root points to
the smaller one.  Returns `false` if `i` and `j` were in the same class
already.
"""
function unite!(parent::Vector{Int}, i::Int, j::Int)
    i, j = minmax(find(parent, i), find(parent, j))
    i < j || return false
    parent[j] = i    # the larger root points to the smaller one
    return true
end

#############################################################################
##
##  Linear Union-Find: linear relations between the basis vectors e_1, e_2, ...
##
##  A dictionary `parent` maps each inactive index i to the sparse vector that
##  replaces e_i, in terms of e_j, j < i.  The index i is active if it is
##  not a key of `parent`.
##

##  the index k of the last inactive position v.poss[k] of v, or 0
lastDead(parent::Dict, v::SparseVec) =
    something(findlast(i -> haskey(parent, i), v.poss), 0)

"""
    find(parent::Dict, v::SparseVec)

The canonical form of `v` modulo the relations in `parent`: the unique vector
in `v + U` that involves active positions only, where `U` is the subspace
spanned by the relations.
"""
function find(parent::Dict, v::SparseVec)
    while (k = lastDead(parent, v)) > 0
        i = v.poss[k]
        v -= v.vals[k] * (unitVec(eltype(v), i) - parent[i])   # replace e_i by parent[i]
    end
    return v
end

"""
    unite!(parent::Dict, u::SparseVec, w::SparseVec)

Add the relation `u = w` to `parent`: reduce `u - w`, and solve the result
for its last position, which then becomes inactive.  Returns `false` if the
relation follows from the earlier ones.  The coefficient at the last position
must be invertible.
"""
function unite!(parent::Dict, u::SparseVec, w::SparseVec)
    v = find(parent, u - w)                    # the relation u = w, reduced
    length(v) > 0 || return false
    i, c = v.poss[end], v.vals[end]            # the last position of v ...
    parent[i] = unitVec(eltype(v), i) - v / c  # ... is replaced by the others
    return true
end

end # module
