#############################################################################
##
#A  unionfind.jl                                                      OrbitAl
#B    by Götz Pfeiffer <goetz.pfeiffer@universityofgalway.ie>
##
#C  Union-Find, for equivalence relations and for linear relations
##
module unionfind

using ..sparsevec

export find, unite!, isunit

#############################################################################
##
##  Union-Find: an equivalence relation on 1:n, generated by pairs.
##
##  A forest is a list `parent` with `parent[i] == i` if `i` is a root.
##
"""
    find(parent::Vector{Int}, i)

The root of `i` in the forest `parent` is the smallest element of its class.
"""
function find(parent::Vector{Int}, i::Int)
    while parent[i] != i
        i = parent[i]
    end
    return i
end

"""
    unite!(parent::Vector{Int}, i, j)

Add the relation `i ~ j` to the forest `parent`: the larger root points to
the smaller one.  Returns the larger root, which is no longer a root, or `0`
if `i` and `j` were in the same class already.
"""
function unite!(parent::Vector{Int}, i::Int, j::Int)
    i, j = minmax(find(parent, i), find(parent, j))
    i < j || return 0
    parent[j] = i    # the larger root points to the smaller one
    return j
end

#############################################################################
##
##  Linear Union-Find: linear relations between the basis vectors e_1, e_2, ...
##
##  A dictionary `parent` maps each inactive index i to the sparse vector that
##  replaces e_i, in terms of the indices that were active when i became
##  inactive.  The index i is active if it is not a key of `parent`.
##
##  A relation is solved for its last position with a unit coefficient: over
##  a field, simply its last position, and then parent[i] involves e_j, j < i,
##  only.  Coefficient types with non-units extend `isunit`.
##

"""
    isunit(c)

Whether the coefficient `c` is invertible.  The default, `!iszero(c)`, is
right for fields; coefficient types with non-units add their own method.
"""
isunit(c) = !iszero(c)

##  the index k of the last inactive position v.poss[k] of v, or 0
lastDead(parent::Dict, v::SparseVec) =
    something(findlast(i -> haskey(parent, i), v.poss), 0)

"""
    find(parent::Dict, v::SparseVec)

The canonical form of `v` modulo the relations in `parent`: the unique vector
in `v + U` that involves active positions only, where `U` is the subspace
(or submodule) spanned by the relations, provided that `unite!` could solve
each of them.
"""
function find(parent::Dict, v::SparseVec)
    while (k = lastDead(parent, v)) > 0
        i = v.poss[k]
        v -= v.vals[k] * (unitVec(eltype(v), i) - parent[i])   # replace e_i by parent[i]
    end
    return v
end

"""
    unite!(parent::Dict, u::SparseVec, w::SparseVec)

Add the relation `u = w` to `parent`: reduce `u - w`, and solve the result
for its last position with a unit coefficient (see [`isunit`](@ref)), which
then becomes inactive.  Returns that position, or `0` if the relation follows
from the earlier ones, or `-1` if no coefficient is a unit, so that the
relation cannot be solved (yet).

Coefficients multiply from the left, so that the coefficients may come from a
non-commutative ring, acting on the left.
"""
function unite!(parent::Dict, u::SparseVec, w::SparseVec)
    v = find(parent, u - w)                    # the relation u = w, reduced
    length(v) > 0 || return 0
    k = findlast(isunit, v.vals)               # the last position with a unit coefficient ...
    isnothing(k) && return -1
    i, c = v.poss[k], v.vals[k]
    parent[i] = unitVec(eltype(v), i) - inv(c) * v   # ... is replaced by the others
    return i
end

end # module
