name: Documentation

on:
  push:
    branches:
      - main  # or master, whichever your default branch is

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required to push to gh-pages

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required for Documenter

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Install dependencies
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path="."))
            Pkg.instantiate()
          '

      - name: Build and deploy docs
        run: |
          julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
